sudo: false
language: python
dist: xenial
matrix:
  include:
    - python: '3.7'
install:
  - pip install -r requirements.txt
  - pip install "ltd-conveyor>=0.4.2,<0.5"
script:
  - sphinx-build -b html -a -n -d _build/doctree . _build/html
after_success:
  - ltd upload --travis --dir _build/html --product ittn-003
env:
  global:
    -
      # LTD_AWS_ID
      secure: SfHBnan5GlAceT1RxGcSNXD8cJ4X7pWdpsol9AVINaLMaeHiX8SFbi+7qm0spJPQ6swMIMxO1EVH4ZMzrNGhaUscBtpEcrsteCn4Ia2XXfLUdjetEkABefgZSQfZheEhxtWdFpdE6tTfdtPQ41zekUVbDmoXJXxtswyETx2twbZE70EU0MKWog5bV1osO71Jnd6G2WiAXVtbSQ74bzHkLONSzIBnjUuggQ7HGbEaOJf13YgBNnT6A9RHGTXoM2k7nvFeaSx2RQ1LaH5cmn7CggUbB7vmLNauMJsiGZn0AKtW2qihR/SnF1LdhuMtml9bCeM4R05v60NC6dGJ3bdo46IwDlunjyzbSJlF8YE6GwhmMH2PAK6yX5LMt4zDX4H8UnXAzgDgbhErbx7ceufuLDX3DBHym+7Fv+DDe2Bmi1yYC1lhFt2cOIj2eXkTHEbbQMYXcuvMOetoKbEUa2Kpic0cFDzMLqKrMm6tTf5U3HOQZfmVU22Tw41kjZ2V1Q2R9n4ylozSv1wnO+GZzg5gWpn27ZLcMz/BXSw9+kviHwyj6kIuZ7YXKiXYTWDKMSE/OlSnsLqAMPhytYrC/wkqhOUw+q+dsEeA23q6+wmIo8xwYXBvS9kcNMyz5ryunONpBlniKjQHVWt2Pbv0Sh10IuGFG19Oc7ZcWZVzjYHZ2PY=
    -
      # LTD_AWS_SECRET
      secure: qOVWGoePRoFV2BnGq1sCm/Odp64VQxKD1F3ZisB6t/X13x8ZwKaXmQYiOpGz/SP9r9DLj8a9EDvOBH2YWZgPcjAbmFvz9SqpqCY32z59jY+DSXJiH4IZTHBnPlUyoeg7PESKFcEHHnBvpiS+1nXSXxCeNfh8HMuKReBT7TrT8rDFfKfrICjH9qLgRu6XzcBznLbUkvLRCNpH+p1HDA6tzt4Z5Or6IxSlW1IYYRzVXdyXLH+MlOIkr04uuRCQgJvBO2hXc9lCmQuHzqYD2N8/iaiIBt9lxV2+jMBrWz51xeNr1tDsgPj5OIFiU0W2ZSWjRJ8ENEsjlXQOoyslJWh7CrUuPytr1raeml9B0cMKbekWRdXv9obbfX4J3xtNls0MaiYEnu1va/3AfIGnRWaWmOxRYG/aFxvl1izgxE7OsjdvX4yvye05nMg8wGrsmLHaUXk8odJHKdeTyblEm+Q6lM+uZFFqIWMPRJPQF5eJAOwaVXp4LJCcyZWPBo7B2TH624GRS0qnlCySJg5fi/4ifWFfavGEDOakrMF1Z8NRlbAC6Eled4dSeLfvyxFmCnj9UwGZd971Gfm2IO2REWgO43tiITnWpN8yCi52yq4be+amQlNoHf09M+H2o+8xBbVSD8RFTnS6n3+/xGGtt3UPu/VzCfiWE+AW9+jkGW+3iHI=
    -
      # LTD_USERNAME
      secure: x5JEd6dtDtFkSKLNmAfzP9jkuR6j0hRwWKYdkVzcr3beNtk+sctMBcS2ySkIE0Id8uQbnEAeG3lPYL/oVomEEbHtFeULBkBIZA+q3mCJPTalhnnw9/1hStIikJOO3WTNz1saQpvFvmA2i9A9aSqNxV12aHGWcI9uvWwBEdt15/Y0sxY0lKjROcG8cuVM0tR2MbKACMbSC4AZ9xAN7APJzgJFSPAOz3hOrznKSYiWTrxfL+El2EabBTpTt1EUCdeALDiQLlfSGSZuzy3r0DjjawtrpPrA0LaALQ+ww7C6hRPIKHM3C+UVMAOvHqbe/Q8x2USa/QqIZAIJuNGDpJoO8PdkZwLiWmPu9WML0K4pEpWra66Hhqm2pSJjzPoygbqRnNLQNKZjOurS1jc5TIyLrllmJkM8DPRzi486VMGB8xp6fj0gvKgElyTdEFmzyZINei/5VNdNPElPvkjhFyZnvgqBrrUZjQ8RZNPCHreq842E0FzSGM+rp8McRGYkhsrscNxiUaU0E6WMKNgNQ+Rlo7B4uOOh5JDq/fCg/e9hDhu5SlzI4HCmG2BqxODKZE80R3QL2JNvARWqd9kRNA00gzJbicRxGsOWBqOxUq/twoSVz1oPcCLWnBIsWWrpzJEQIcgCKgO11Dd0C96bmS5yVL9calBZn9zwP5I25ap2Sp0=
    -
      # LTD_PASSWORD
      secure: x3YXboHM2VF2vWfkuMxJ2Y5Xzb3pIhk9Gi6FO12kVucQOVXhQT1hL2lHy+YpFgi6s6SR7ep25m8lKALdgD/PBo8e8zxYUdeCR5LIhViNK9okA1rnPKMdwe+73bOT0nLU5hQBLsaF56Pju9YE41otEmkPLvrVda9ZZ3xb4SyOtz4+15FDAaw88Qsb2ZzjV/JphlH3okvCOYQSUj9CstY1PamDoi/BCedmg/uwatcJb401zvjkoIqW+uPawVlSDkfu82lHrtbHop8YGcz7IzhPIbBP4r4yKrEccVs4KMSnJzXTEGDM2iMHb3lXMSDs5QhHcPu1RFtoSxXt0AOaWJFWVDJR05nQLd/Ssg9PboeFJ3XZsMLW/i7Odn6bewh1pB5Kk5sasZs1x6m3nSsQS3+J1/6vDA6sU/N28hYzXDrkkThVHAduTmquK6T40qu52oOU/pB9t5QB/HZBQjct34O5Bb+yy+ZsoiRf4p+thmA7c8I9bHd286aIZY6I7rWJC5Euu/VCXpL/LXZlXxgdPH5Uxk+2OxSNrG4RILNTG9DxkEMJ1JK+TFxAyjELI7BU6oGTgj/fkrblzkKAqnagwH9mI2y0dF2TVkw1LNtfY8O/+Ll7CMupheMEmNANUgXCw31uiAmY2jKJHAljY/b0lLW4CcEjkdfrhT7AjOl+OdC+V5A=
